<?php
Route::middleware(['auth'])->group(function ($router) {
    Route::view('motm', 'pages/motm')   ->name('motm');
    $router->get('teams', 'pages\TeamController@teamsList')                     ->name('teams');
    $router->get('teams/toevoegen', 'pages\TeamController@showNewForm')          ->name('create.team.route');
    $router->get('teams/aanpassen/{id}', 'pages\TeamController@showEditForm')    ->name('edit.team.route');
    $router->get('teams/verwijderen/{id}', 'pages\TeamController@remove')        ->name('delete.team.route');
    $router->post('teams/toevoegen', 'pages\TeamController@create')              ->name('create.team');
    $router->post('teams/aanpassen', 'pages\TeamController@edit')                ->name('edit.team');
    $router->post('teams/verwijderen', 'pages\TeamController@remove')            ->name('delete.team');
    $router->get('toernooien', 'pages\TournamentController@tournamentsList')            ->name('tournaments');
    $router->get('toernooi/toevoegen', 'pages\TournamentController@showNewForm')        ->name('create.tournament.route');
    $router->get('toernooi/aanpassen/{id}', 'pages\TournamentController@showEditForm')  ->name('edit.tournament.route');
    $router->get('toernooi/verwijderen/{id}', 'pages\TournamentController@remove')      ->name('delete.tournament.route');
    $router->post('toernooi/toevoegen', 'pages\TournamentController@create')            ->name('create.tournament');
    $router->post('toernooi/aanpassen', 'pages\TournamentController@edit')              ->name('edit.tournament');
    $router->post('toernooi/verwijderen', 'pages\TournamentController@remove')          ->name('delete.tournament');
    $router->get('toernooi/{id}', 'pages\TournamentController@viewTournament')                    ->name('tournament');
    Route::get('profiel', 'Pages\ProfileController@index')                          ->name('profile');
    $router->post('profiel/aanpassen', 'Auth\UpdateUserController@updateUser')      ->name('profile.edit');
    Route::get('profiel/aanpassen', 'Auth\UpdateUserController@editProfilePage')    ->name('profile.edit.route');
    $router->post('uitnodigen', 'Auth\InviteController@invite');
    $router->get('uitnodigen', 'Auth\InviteController@index')   ->name('invite');
    $router->post('uitloggen', 'Auth\LoginController@logout');
    Route::get('uitloggen', 'Auth\LoginController@logout')      ->name('logout');
    Route::get('users/search/{data?}', 'UserController@search');
    Route::get('teams/search/{data?}', 'Pages\TeamController@search');
});
Route::get('/', 'HomeController@index')->name('home');
$router->post('login', 'Auth\LoginController@login');
$router->get('login', 'Auth\LoginController@index') ->name('login');
$router->post('registreren', 'Auth\UpdateUserController@register');
$router->get('registreren/{token}', 'Auth\UpdateUserController@registerPage')   ->name('register');
$router->post('wachtwoord/vergeten', 'Auth\ForgotPasswordController@sendResetLinkEmail')        ->name('forgot.password');
Route::view('wachtwoord/vergeten', 'pages/auth/forgot-password');
$router->post('wachtwoord/aanpassen', 'Auth\ResetPasswordController@ResetPassword');
$router->get('wachtwoord/aanpassen/{token}', 'Auth\ResetPasswordController@showResetForm')        ->name('reset.password.token');
$router->get('wachtwoord/aanpassen', 'Auth\ResetPasswordController@showResetForm')                ->name('reset.password');
